- name: Install and configure Jupyter DockerSpawner
  hosts: localhost
  gather_facts: false
  vars: {}
  tasks:

    - name: Wait for system to become reachable
      wait_for_connection:
        timeout: 300

    - name: Common stuff
      include_role:
        name: common

    - name: Install gcc, git, ntp
      apt:
        update_cache: yes
        pkg:
          - git
          - gcc
          - g++
          - make
          - ntp
          - tmux
          - ksh
          - acl
          - net-tools
          - jq
          - ca-certificates
          - curl
          - software-properties-common
          - apt-transport-https
          - npm
          - nodejs
          - python3-pip

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install configurable http proxy
      npm:
        name: configurable-http-proxy
        global: yes

    - name: Install python packages
      include_role:
        name: python

    - name: Set up Jupyter server
      include_role:
        name: jupyter
