name: Build Docker image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

    - name: checkout files in repo
      uses: actions/checkout@v4

    # container registries require lowercase repo names.
    # https://github.com/orgs/community/discussions/25768
    - name: Lowercase repo name
      run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }} 
        password: ${{ secrets.GITHUB_TOKEN }}  

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: image
        push: true
        tags: |
          ${{ env.REPO }}:${{ github.ref_name }}
          ${{ env.REPO }}:latest
